// Import the `notFound` helper from Next.js to trigger a 404 page
import { notFound } from "next/navigation";

// Import all static project entries generated by Contentlayer
import { allProjects } from "contentlayer/generated";

// Custom MDX rendering component (with pretty-code and styling)
import { Mdx } from "@/app/components/mdx";

// Header component showing title, description, view count, etc.
import { Header } from "./header";

// Import global CSS specific to MDX rendering (pretty code, etc.)
import "./mdx.css";

// Component to track/report views per project
import { ReportView } from "./view";

// Import Upstash Redis client to store and retrieve view counts
import { Redis } from "@upstash/redis";

// Set ISR (Incremental Static Regeneration) to revalidate every 60 seconds
export const revalidate = 60;

// Define the shape of props for this page
type Props = {
  params: {
    slug: string; // URL parameter for project slug (e.g., "fit-sphere")
  };
};

// Create Redis instance using environment variables
const redis = Redis.fromEnv();

// Generate static params for dynamic routes at build time
// Next.js will pre-render one page for each project.slug
export async function generateStaticParams(): Promise<Props["params"][]> {
  return allProjects
    .filter((p) => p.published) // Only include published projects
    .map((p) => ({
      slug: p.slug,
    }));
}

// Main component for rendering an individual project post page
export default async function PostPage({ params }: Props) {
  const slug = params?.slug; // Extract slug from URL params

  // Find the project in the generated list using the slug
  const project = allProjects.find((project) => project.slug === slug);

  // If no match is found, return 404 page
  if (!project) {
    notFound();
  }

  // Retrieve view count from Redis (e.g., "pageviews:projects:fit-sphere")
  const views =
    (await redis.get<number>(["pageviews", "projects", slug].join(":"))) ?? 0;

  // Return the rendered page
  return (
    <div className="bg-zinc-50 min-h-screen">
      {/* Project header (title, description, views, etc.) */}
      <Header project={project} views={views} />

      {/* Report pageview to analytics/logging system */}
      <ReportView slug={project.slug} />

      {/* Render the project content (markdown → HTML via MDX) */}
      <article className="px-4 py-12 mx-auto prose prose-zinc prose-quoteless">
        <Mdx code={project.body.code} />
      </article>
    </div>
  );
}