// This marks the file as a Client Component (needed for using hooks and browser APIs)
"use client";

// Import React hooks and icon components
import { useState, useRef, useEffect } from "react";
import { MessageCircle, X, Maximize2, Minimize2 } from "lucide-react";

// Define the ChatBot component
export function ChatBot() {
  // State to control whether the chatbot window is open
  const [isOpen, setIsOpen] = useState(false);

  // State to control whether the window is expanded or minimized
  const [isExpanded, setIsExpanded] = useState(false);

  // Stores the array of messages between user and assistant
  const [messages, setMessages] = useState<{ role: string; content: string }[]>([]);

  // Controlled input value for the user's typed message
  const [input, setInput] = useState("");

  // Tracks whether a response is currently being generated by the assistant
  const [loading, setLoading] = useState(false);

  // Controls whether the "Ask Grace!" hint bubble is visible
  const [showHint, setShowHint] = useState(false);

  // Ref to scroll to the bottom of the message list when a new message appears
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  // Handles sending the message to the backend API and displaying the response
  const sendMessage = async () => {
    // Prevent sending empty messages
    if (!input.trim()) return;

    // Create user message object
    const userMessage = { role: "user", content: input };

    // Add user's message to the messages array
    setMessages((prev) => [...prev, userMessage]);

    // Clear the input field
    setInput("");

    // Set loading state to true while waiting for AI response
    setLoading(true);

    // Send the message history to the chat-bot API
    const res = await fetch("/api/chat-bot", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ messages: [...messages, userMessage] }),
    });

    // Get the JSON response
    const data = await res.json();

    // Add the assistant's reply to the messages array
    setMessages((prev) => [...prev, { role: "assistant", content: data.reply }]);

    // Turn off loading state
    setLoading(false);
  };

  // Automatically scroll to the bottom of the chat when messages or loading state change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  // Show the "Ask Grace!" tooltip on initial load for 10 seconds
  useEffect(() => {
    setShowHint(true);
    const timer = setTimeout(() => setShowHint(false), 10000);
    return () => clearTimeout(timer); // Clean up timer on component unmount
  }, []);

  return (
    // Position chatbot fixed at bottom right of the screen
    <div className="fixed bottom-6 right-6 z-50">
      {isOpen ? (
        // Chat window when opened
        <div
          className={`bg-white border border-gray-200 flex flex-col rounded-lg shadow-lg p-4 transition-all duration-300 ${
            isExpanded
              ? "w-[90vw] h-[80vh] max-w-4xl"
              : "w-[400px] h-[300px] max-w-lg"
          }`}
        >
          {/* Header: title and control buttons */}
          <div className="flex justify-between items-center mb-2">
            <span className="font-bold text-pink-500">Ask Me Anything!</span>
            <div className="flex items-center space-x-2">
              {/* Expand/minimize button */}
              <button onClick={() => setIsExpanded(!isExpanded)}>
                {isExpanded ? (
                  <Minimize2 className="text-gray-400 hover:text-pink-600" size={20} />
                ) : (
                  <Maximize2 className="text-gray-400 hover:text-pink-600" size={20} />
                )}
              </button>
              {/* Close button */}
              <button onClick={() => setIsOpen(false)}>
                <X className="text-gray-400 hover:text-pink-600" size={20} />
              </button>
            </div>
          </div>

          {/* Chat messages display area */}
          <div className="flex-grow overflow-y-auto mb-2 text-sm">
            {messages.map((m, i) => (
              <div
                key={i}
                className={`mb-2 ${
                  m.role === "user" ? "text-right" : "text-left text-pink-600"
                }`}
              >
                <p>{m.content}</p>
              </div>
            ))}
            {/* Loading indicator */}
            {loading && (
              <div className="text-left text-pink-400 italic text-sm mb-2">
                Grace is typing...
              </div>
            )}
            {/* Scroll target */}
            <div ref={messagesEndRef} />
          </div>

          {/* Input area */}
          <form
            onSubmit={(e) => {
              e.preventDefault(); // Prevent page reload
              sendMessage();      // Send the message
            }}
            className="flex"
          >
            {/* Text input */}
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask Grace..."
              className="flex-1 border p-2 rounded-l text-sm"
            />
            {/* Submit button */}
            <button
              type="submit"
              className="bg-pink-500 text-white px-4 rounded-r text-sm hover:bg-pink-600"
            >
              Send
            </button>
          </form>
        </div>
      ) : (
        // Floating chat button when closed
        <div className="relative">
          {/* Hint tooltip bubble */}
          {showHint && (
            <div className="absolute bottom-14 right-0 bg-white text-gray-800 text-sm border border-gray-300 px-4 py-2 rounded-lg shadow-lg w-max">
              Ask Grace!
            </div>
          )}

          {/* Chat icon button */}
          <button
            onClick={() => setIsOpen(true)} // Open chat window
            className="bg-pink-500 hover:bg-pink-600 text-white p-3 rounded-full shadow-lg flex items-center justify-center animate-pulse"
            aria-label="Open ChatBot"
          >
            <MessageCircle size={24} />
          </button>
        </div>
      )}
    </div>
  );
}